# Put the location of your BMS install here, e.g. D:\Games\Falcon BMS 4.38
bms_location = test

# Specify your BMS callsign.
callsign = wsy

# This is a list of pages, you can add/delete new ones and reorder the content. Possible content values are: 
# airbase, package, flightplan, roster, admin, weapon_settings, cmds, targets, delivery, aa_brevity_notes, support,
# weapons, tgtsteerpoints, wpn_targets, roe, weather, map, comms, custom_checklist (for the last one to be meaningful you need to modify the template)
page = airbase, package, flightplan 
page = roster, admin, cmds, targets, tgtsteerpoints, wpn_targets, weapon_settings, delivery, aa_brevity_notes, roe
page = weapons, support
page = comms, weather
page = map

# If this value is set to False, each page is rendered to a separate HTML. If it is set to True, all pages are rendered into a single HTML. 
# A modern browser's Print to PDF function should separate the pages correctly.
# Alternative: launch option "-s" or "--separated" is equivalent to joined = False
joined = True

# Set this to True if you want the script to monitor the changes to briefing.txt and callsign.ini and run automatically. 
# Alternative: launch option "-m" or "--monitor"
monitor = True